name: Validate Partner Registry

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - 'main'

jobs:
    validate:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '18'

            - name: Install dependencies
              run: npm install

            - name: Compile TypeScript
              run: npm run build

            - name: Check partners are valid
              id: check-partners
              run: |
                  # Capture logs via tee so they are in GH Actions logs
                  npm run check-partners 2>&1 | tee check-partners-output.txt

                  # Now set that as an output so a later step can parse or use it
                  echo "VALIDATION_RESULTS<<EOF" >> "$GITHUB_OUTPUT"
                  cat check-partners-output.txt >> "$GITHUB_OUTPUT"
                  echo "EOF" >> "$GITHUB_OUTPUT"
