name: Scheduled CDN Upload
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  run-npm-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Compile TypeScript
        run: npm run build
      - name: Check partners are valid
        run: npm run failure-test
      - name: Generate partner list
        run: npm run generate
      - name: Upload to CDN
        env:  
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          FILE_PATH: ${{ secrets.FILE_PATH }}
          OBJECT_KEY: ${{ secrets.OBJECT_KEY }}
          REGION: ${{ secrets.REGION }}
        run: npm run upload
